name: continuous-delivery

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN}} ## !!! DO NOT RENAME AS IS USED TO AUTHENTICAT GITHUB TFM PROVIDER 

  PIXEL_CORE_AWS_ACCESS_KEY_ID: ${{ secrets.PIXEL_CORE_GITHUB_AWS_ACCESS_KEY_ID }}
  PIXEL_CORE_AWS_SECRET_ACCESS_KEY: ${{ secrets.PIXEL_CORE_GITHUB_AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ secrets.AWS_REGION }}

jobs:

  get-repos-changed:
    name: get-repos-changed
    runs-on: ubuntu-latest
    outputs:
      repos_modified: ${{ steps.get-repos.outputs.repos_modified }}
    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: get-changed-files
        with:
          list-files: shell
          filters: |
            repos:
              - added|modified: "repos/*/*.tfvars"
            terraform:
              - added|modified: "terraform/**"
      - name: Get repos Modified
        id: get-repos
        run: |
          export repos_modified="${{ steps.get-changed-files.outputs.repos }}"
          export repos_files="${{ steps.get-changed-files.outputs.repos_files }}"
          export terraform_changed="${{ steps.get-changed-files.outputs.terraform }}"
          ./scripts/detect-changes.sh

  tfm-apply:
    name: tfm-apply
    runs-on: ubuntu-latest
    needs: get-repos-changed
    if: needs.get-repos-changed.outputs.repos_modified != 'none'
    strategy:
      matrix: ${{ fromJSON( needs.get-repos-changed.outputs.repos_modified ) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pixel-systems/tfm-plan-gh-action@PIXEL-tfm-cloud
        name: terraform plan
        env:
          BACKEND_FILE: "./repos/${{ matrix.repos }}/backend.tfvars"
          TF_VARS_FILE: "./repos/${{ matrix.repos }}/resources.tfvars"
        with:
          region: $REGION
          access-key: $PIXEL_CORE_AWS_ACCESS_KEY_ID
          secret-key: $PIXEL_CORE_AWS_SECRET_ACCESS_KEY
          terraform-folder: "terraform"
          backend-configuration: "$BACKEND_FILE"
          terraform-var-file: "$TF_VARS_FILE"
          terraform-plan-file: "terraform/tfplan"
      - uses: ohpensource/terraform-apply-gh-action/action@0.0.0.1
        name: terraform apply
        env:
          BACKEND_FILE: "./repos/${{ matrix.repos }}/backend.tfvars"
          TF_VARS_FILE: "./repos/${{ matrix.repos }}/resources.tfvars"
        with:
          region: $REGION
          access-key: $PIXEL_CORE_AWS_ACCESS_KEY_ID
          secret-key: $PIXEL_CORE_AWS_SECRET_ACCESS_KEY
          terraform-folder: "terraform"
          backend-configuration: "$BACKEND_FILE"
          terraform-plan-file: "terraform/tfplan"
          terraform-outputs-file: "terraform/outputs.json"
